chore(dynamo): do not rebuild dynamo plugin
otherwise, plugin is not exported within a default key and we get:
TypeError: Plugin is not a constructor

sourceType:'unambiguous' removed from webpackconfig since "exports is not defined" (see PR description https://github.com/hubtype/botonic/pull/937) is not appearing anymore